name: Monthly Docker Build
concurrency:
  group: build-release
  cancel-in-progress: true
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Run PowerShell script to get versions
      run: |
        $versions = & ./.github/workflows/get-versions.ps1
        if ($versions.Count -eq 0) {
          Write-Host "No versions found. Skipping Docker build and push."
          exit 0
        }
        Write-Host "Versions found: $($versions -join ', ')"
        $versions | ForEach-Object {
          docker build --build-arg K8SVersion=$_ -t archetypicalsoftware/vega-utility:$_ .
          docker push archetypicalsoftware/vega-utility:$_
        }
        Write-Host "Tagging and pushing latest version"
        docker tag archetypicalsoftware/vega-utility:$($versions[0]) archetypicalsoftware/vega-utility:latest
        docker push archetypicalsoftware/vega-utility:latest
      shell: pwsh
